name = "Skelia"
uuid = "79462ac6-003b-4e37-94c5-db11fbae63d8"
authors = ["Mayumi"]
version = "0.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
